### ISSUE TITLE
Option to turn on the progress bar?

### ISSUE THREAD

**Issue by alexvorobiev** [HenrikBengtsson/future.BatchJobs#65]
I see that the progress bar is disabled unless the debug mode is chosen. 

https://github.com/HenrikBengtsson/future.BatchJobs/blob/master/R/BatchJobsFuture-class.R#L46

Is there any way to make it visible?

**Comment by HenrikBengtsson** [comment]
Your referring to the fact that `BBmisc.ProgressBar.style="off"` unless debug is enabled. Yes, this is the current behavior, which is mostly / simply because I haven't put much thought into it.

However, over in future itself there's also code for handling progress bar output for other type of futures. My hope is to be able to generalize this such that it will work the same everywhere. Before that is in place, I could probably add more direct support for the BatchJobs-specific progress bars in this package. I'll add it to the to-do list.

**Comment by HenrikBengtsson** [comment]
@alexvorobiev, the develop branch (will be part of the next release) now provides an option to control what you want.  If you set:
```r
options(future.BatchJobs.output = TRUE)
```
the package will avoid setting option `BBmisc.ProgressBar.style="off"`.  For example,
```r
> library("future.BatchJobs")
> plan(batchjobs_local)
> x %<-% 42
> x
[1] 42

> options(future.BatchJobs.output = TRUE)
> x %<-% 42
Creating dir: /home/hb/repositories/future.BatchJobs/.future/20161019_183847-k6qh1p/BatchJobs_557388419-files
Saving registry: /home/hb/repositories/future.BatchJobs/.future/20161019_183847-k6qh1p/BatchJobs_557388419-files/registry.RData
Adding 1 jobs to DB.
Saving conf: /home/hb/repositories/future.BatchJobs/.future/20161019_183847-k6qh1p/BatchJobs_557388419-files/conf.RData
Submitting 1 chunks / 1 jobs.
Cluster functions: Local.
Auto-mailer settings: start=none, done=none, error=none.
Writing 1 R scripts...
SubmitJobs |+++++++++++++++++++++++++++++++++++++++++++++++++| 100% (00:00:00)
Sending 1 submit messages...
Might take some time, do not interrupt this!
> x
Syncing registry ...
[1] 42

> options(future.BatchJobs.output = FALSE)
> x %<-% 42
> x
[1] 42
```

**Comment by HenrikBengtsson** [comment]
Just in case someone else sees this too; it's possible to show only progress bar (and no other BatchJobs outputs) by:
```r
> library("future.BatchJobs")
Loading required package: future
> plan(batchjobs_local)
> options(BatchJobs.verbose = FALSE)
> options(future.BatchJobs.output = TRUE)
> x %<-% 42
SubmitJobs |+++++++++++++++++++++++++++++++++++++++++++++++++| 100% (00:00:00)
> x
[1] 42
> 
```

**Comment by alexvorobiev** [comment]
@HenrikBengtsson Thanks for the feature, the progress bar is very useful for interactive sessions.
